version: '3'

services:

  ubuntu_20.04:
    build:
      context: .
      dockerfile: .docker/Dockerfile-ubuntu_20.04
    volumes:
      - .:/root/wkhtmltopdf_binary_gem

  debian_10:
    build:
      context: .
      dockerfile: .docker/Dockerfile-debian_10
    volumes:
      - .:/root/wkhtmltopdf_binary_gem
